# Generated by Django 5.1.15 on 2026-07-13 15:16

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaptureToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(default='iPhone', max_length=60)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.BinaryField()),
                ('gtd_calendar_id', models.CharField(blank=True, max_length=120)),
                ('primary_calendar_id', models.CharField(default='primary', max_length=120)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_directly', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10, unique=True)),
                ('weekday', models.PositiveSmallIntegerField(default=4)),
                ('time', models.TimeField(default=datetime.time(16, 0))),
                ('duration_min', models.PositiveSmallIntegerField(default=60)),
                ('gcal_event_id', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase_state', models.JSONField(blank=True, default=dict)),
                ('stats_snapshot', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SyncChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(max_length=120)),
                ('channel_id', models.UUIDField()),
                ('resource_id', models.CharField(max_length=120)),
                ('expiration', models.DateTimeField()),
                ('sync_token', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=40, unique=True)),
                ('is_context', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.note')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'ref_id', 'sent_at'], name='core_notifi_kind_a8c555_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('rrule', models.CharField(max_length=200)),
                ('block_start_time', models.TimeField(blank=True, null=True)),
                ('block_duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gcal_event_id', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('last_materialized_until', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('list', models.CharField(choices=[('next', 'Next'), ('waiting', 'Waiting'), ('someday', 'Someday'), ('trash', 'Trash')], default='next', max_length=10)),
                ('is_project', models.BooleanField(default=False)),
                ('is_next_action', models.BooleanField(default=False)),
                ('horizon', models.CharField(choices=[('today', 'Today'), ('this_week', 'Week'), ('this_month', 'Month'), ('anytime', 'Anytime')], default='anytime', max_length=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('big3', models.BooleanField(default=False)),
                ('q2_week', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('waiting_on', models.CharField(blank=True, max_length=120)),
                ('waiting_since', models.DateField(blank=True, null=True)),
                ('follow_up_after_days', models.PositiveSmallIntegerField(default=5)),
                ('last_follow_up_nag', models.DateField(blank=True, null=True)),
                ('carried_over_count', models.PositiveSmallIntegerField(default=0)),
                ('missed_block_count', models.PositiveSmallIntegerField(default=0)),
                ('occurrence_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task')),
                ('recurring_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='core.recurringtemplate')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('missed', 'Missed'), ('completed', 'Completed')], default='scheduled', max_length=10)),
                ('gcal_event_id', models.CharField(blank=True, max_length=120)),
                ('gcal_etag', models.CharField(blank=True, max_length=120)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['trashed_at'], name='core_note_trashed_a469d3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='core_note_search_0320e4_gin'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['list', 'horizon'], name='core_task_list_e62bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed_at'], name='core_task_complet_afc3ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_project', True), _negated=True), ('parent__isnull', True), _connector='OR'), name='no_project_subtask'),
        ),
    ]
