# Generated by Django 5.1.15 on 2026-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_template__isnull', False)), fields=('recurring_template', 'occurrence_date'), name='unique_recurring_occurrence'),
        ),
    ]
