# Generated by Django 5.1.15 on 2026-07-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_unique_recurring_occurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
