# Generated by Django 5.1.15 on 2026-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projecttemplate_note_linked_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='energy',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
