from functools import partial

from django.urls import path

from . import clarify, google_calendar, lists, notes, projects, recurring, reviews, stats, tags, timeblocks, views

# Named routes referenced by base.html nav. Real implementations land in
# their own epics (see docs/task-breakdown.md); until then each renders
# a plain stub so nothing 404s while the shell is being built.
urlpatterns = [
    path("inbox/", views.inbox_page, name="inbox"),
    path("inbox/process/", clarify.process_start, name="inbox_process"),
    path("inbox/process/<int:pk>/", clarify.clarify_actionable, name="clarify_actionable"),
    path("inbox/process/<int:pk>/no/", clarify.clarify_not_actionable, name="clarify_not_actionable"),
    path("inbox/process/<int:pk>/trash/", clarify.clarify_trash, name="clarify_trash"),
    path("inbox/process/<int:pk>/someday/", clarify.clarify_someday, name="clarify_someday"),
    path("inbox/process/<int:pk>/reference/", clarify.clarify_reference, name="clarify_reference"),
    path("inbox/process/<int:pk>/yes/", clarify.clarify_actionable_type, name="clarify_actionable_type"),
    path("inbox/process/<int:pk>/done/", clarify.clarify_done, name="clarify_done"),
    path("inbox/process/<int:pk>/single/", clarify.clarify_single, name="clarify_single"),
    path("inbox/process/<int:pk>/project/", clarify.clarify_project, name="clarify_project"),
    path("inbox/process/<int:pk>/delegate/", clarify.clarify_delegate, name="clarify_delegate"),
    path("inbox/items/", views.inbox_item_create, name="inbox_item_create"),
    path("inbox/items/<int:pk>/done/", views.inbox_item_done, name="inbox_item_done"),
    path("capture/", views.capture_page, name="capture"),
    path("capture/modal/", views.capture_modal, name="capture_modal"),
    path("today/", lists.today_view, name="today"),
    path("week/", lists.week_view, name="week"),
    path("month/", lists.month_view, name="month"),
    path("tasks/", lists.tasks_view, name="tasks"),
    path("projects/", projects.projects_view, name="projects"),
    path("projects/<int:pk>/", projects.project_detail, name="project_detail"),
    path("projects/<int:pk>/subtasks/", projects.project_add_subtask, name="project_add_subtask"),
    path(
        "projects/<int:pk>/subtasks/<int:subtask_pk>/flag/",
        projects.project_flag_next,
        name="project_flag_next",
    ),
    path("waiting/", lists.waiting_view, name="waiting"),
    path("waiting/<int:pk>/got-it/", lists.waiting_got_it, name="waiting_got_it"),
    path("waiting/<int:pk>/nudge/", lists.waiting_nudge, name="waiting_nudge"),
    path("someday/", lists.someday_view, name="someday"),
    path("someday/<int:pk>/activate/", lists.someday_activate, name="someday_activate"),
    path("notes/", notes.notes_view, name="notes"),
    path("notes/new/", notes.note_create, name="note_create"),
    path("notes/<int:pk>/", notes.note_detail, name="note_detail"),
    path("notes/<int:pk>/update/", notes.note_update, name="note_update"),
    path("notes/<int:pk>/delete/", notes.note_delete, name="note_delete"),
    path("notes/<int:pk>/attachments/", notes.note_attachment_upload, name="note_attachment_upload"),
    path(
        "notes/<int:pk>/attachments/<int:attachment_pk>/download/",
        notes.note_attachment_download,
        name="note_attachment_download",
    ),
    path(
        "notes/<int:pk>/attachments/<int:attachment_pk>/delete/",
        notes.note_attachment_delete,
        name="note_attachment_delete",
    ),
    path("tasks/<int:pk>/convert-to-note/", notes.task_convert_to_note, name="task_convert_to_note"),
    path("recurring/", recurring.recurring_view, name="recurring"),
    path("recurring/new/", recurring.recurring_create, name="recurring_create"),
    path("recurring/<int:pk>/", recurring.recurring_detail, name="recurring_detail"),
    path("recurring/<int:pk>/edit/", recurring.recurring_edit, name="recurring_edit"),
    path("recurring/<int:pk>/deactivate/", recurring.recurring_deactivate, name="recurring_deactivate"),
    path("recurring/<int:pk>/activate/", recurring.recurring_activate, name="recurring_activate"),
    path(
        "recurring/<int:pk>/overdue/complete/",
        recurring.recurring_complete_overdue,
        name="recurring_complete_overdue",
    ),
    path(
        "recurring/<int:pk>/overdue/trash/",
        recurring.recurring_trash_overdue,
        name="recurring_trash_overdue",
    ),
    path("tags/", tags.tags_view, name="tags"),
    path("tags/<int:pk>/toggle-context/", tags.tag_toggle_context, name="tag_toggle_context"),
    path("tags/<int:pk>/rename/", tags.tag_rename, name="tag_rename"),
    path("tags/<int:pk>/merge/", tags.tag_merge, name="tag_merge"),
    path("tags/<int:pk>/delete/", tags.tag_delete, name="tag_delete"),
    path("review/", reviews.review_dashboard, name="review_dashboard"),
    path("review/", reviews.review_dashboard, name="review"),
    path("review/config/<str:cadence>/save/", reviews.review_config_save, name="review_config_save"),
    path("review/config/<str:cadence>/delete/", reviews.review_config_delete, name="review_config_delete"),
    path("review/weekly/", reviews.review_weekly_start, name="review_weekly_start"),
    path("review/weekly/<str:phase>/", reviews.review_weekly_phase, name="review_weekly_phase"),
    path(
        "review/carryover/<int:pk>/<str:action>/",
        reviews.review_carryover_resolve,
        name="review_carryover_resolve",
    ),
    path(
        "review/eisenhower/<int:pk>/drop/<str:quadrant>/",
        reviews.review_eisenhower_drop,
        name="review_eisenhower_drop",
    ),
    path("review/monthly/", reviews.review_monthly_start, name="review_monthly_start"),
    path("review/monthly/<str:phase>/", reviews.review_monthly_phase, name="review_monthly_phase"),
    path("review/<str:cadence>/", reviews.review_simple_start, name="review_simple_start"),
    path("review/<str:cadence>/<str:phase>/", reviews.review_simple_phase, name="review_simple_phase"),
    path("stats/", stats.stats_view, name="stats"),
    path("settings/", views.settings_page, name="settings"),
    path("settings/tokens/", views.capture_token_create, name="capture_token_create"),
    path("settings/tokens/<int:pk>/revoke/", views.capture_token_revoke, name="capture_token_revoke"),
    path("settings/notifications/<str:kind>/toggle/", views.notification_toggle, name="notification_toggle"),
    path("settings/notifications/<str:kind>/test/", views.notification_test_fire, name="notification_test_fire"),
    path("settings/google/connect/", google_calendar.google_connect, name="google_connect"),
    path("google/callback", google_calendar.google_callback, name="google_callback"),
    path("settings/google/disconnect/", google_calendar.google_disconnect, name="google_disconnect"),
    path("gcal/webhook", google_calendar.gcal_webhook, name="gcal_webhook"),
    path("trash/", lists.trash_view, name="trash"),
    path("tasks/<int:pk>/restore/", lists.task_restore, name="task_restore"),
    path("tasks/<int:pk>/purge/", lists.task_purge, name="task_purge"),
    path("tasks/<int:pk>/complete/", lists.task_complete, name="task_complete"),
    path("tasks/<int:pk>/reopen/", lists.task_reopen, name="task_reopen"),
    path("tasks/<int:pk>/move/<str:target>/", lists.task_move, name="task_move"),
    path("tasks/<int:pk>/flag-next/", lists.task_flag_next, name="task_flag_next"),
    path("tasks/<int:pk>/horizon/<str:horizon>/", lists.task_set_horizon, name="task_set_horizon"),
    path("tasks/<int:pk>/reorder/", lists.task_reorder, name="task_reorder"),
    path("calendar/", timeblocks.calendar_page, name="calendar_page"),
    path("calendar/events.json", timeblocks.calendar_events_json, name="calendar_events_json"),
    path("tasks/<int:task_pk>/blocks/", timeblocks.timeblock_create, name="timeblock_create"),
    path("blocks/<int:pk>/update/", timeblocks.timeblock_update, name="timeblock_update"),
    path("blocks/<int:pk>/delete/", timeblocks.timeblock_delete, name="timeblock_delete"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("", lists.today_view, name="home"),
]
